### ISSUE TITLE
Multiple Custom Alarm Sounds

### ISSUE THREAD

**Issue by 34486** [World-Control-Team/World-Control#28] opened 2019-12-25 00:54 UTC
Hello, I have followed the format given by the wiki, and was able to get one sound to work, but the others I have do not work.
The code follows as this:
{ sound here } 
{ sound here }

I have opening and closing. Its like everything added after the first sound doesn't work. I was able to get all the sounds to work individually, so it is actually able to play it, it just wont let me play multiple of them.

1.12.2 2846.

Thank you very much!

**Comment by xbony2** [comment] 2019-12-25 02:22
what's the code?

**Comment by 34486** [comment] 2019-12-29 14:53
[sounds.txt](https://github.com/World-Control-Team/World-Control/files/4008150/sounds.txt)

It is a .json for the real config, I had to change it to .txt to upload. 

The first sound I put in the first line works, but anything after it will not. I am probably missing something obvious.

**Comment by xbony2** [comment] 2019-12-29 23:40
Yeah I think you're suppose to do something more like
```json
{
"alarm-fusion": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-fusion", "stream": true}]},
"alarm-me": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-me", "stream": true}]},
"alarm-power": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-power", "stream": true}]},
"alarm-power2": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-power2", "stream": true}]},
"alarm-water": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-water", "stream": true}]}
```

**Comment by 34486** [comment] 2020-01-02 22:12
I had tried that before, but I put your code in, and none of my sounds work again. Only the two default swhen I select fusion and me.

**Comment by xbony2** [comment] 2020-01-03 05:56
well i guess something isn't working

**Comment by dmf444** [comment] 2020-02-16 16:27
Hello, 
Sorry for the wait, but I need some more data.
Can you post your worldcontrol.cfg file?

**Comment by 34486** [comment] 2020-03-05 16:52
[wc.zip](https://github.com/World-Control-Team/World-Control/files/4294082/wc.zip)

wouldnt let me upload as cfg and i dont want formatting to break in .txt so there it is in a .zip

Thank you!
Also, I have not tried yet, would be be possible for me to make recipes for this mod using something like minetweaker, or is it not supported?

**Comment by JellyDoge** [comment] 2020-03-06 21:06
Having the same problem as well. I tried first with multiple alarms but spent an hour trying different things and can't get any to work.
[sounds.json](https://pastebin.com/dRBDahq6)
[worldcontrol.cfg](https://pastebin.com/tuC5Q35e)
[sound files](https://i.imgur.com/er00ai9.png)

**Comment by Screeching-Noises** [comment] 2020-04-09 22:48
> Yeah I think you're suppose to do something more like
> 
> ```json
> {
> "alarm-fusion": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-fusion", "stream": true}]},
> "alarm-me": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-me", "stream": true}]},
> "alarm-power": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-power", "stream": true}]},
> "alarm-power2": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-power2", "stream": true}]},
> "alarm-water": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-water", "stream": true}]}
> ```

I'm _definitely_ not an expert here, but it looks like the issue is that it's missing a closing bracket. Going on that logic, 34486's original file only read the first sound [because it was enclosed in its own curly bracket] and ignored the rest for a similar reason.
Could be wrong though.

To get it to work, I'm guessing you do

```
{
"alarm-fusion": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-fusion", "stream": true}]},
"alarm-me": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-me", "stream": true}]},
"alarm-power": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-power", "stream": true}]},
"alarm-power2": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-power2", "stream": true}]},
"alarm-water": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-water", "stream": true}]}
}
```

EDIT: it seems that configuration does not work either.

**Comment by 34486** [comment] 2020-04-12 16:02
Yeah idk. The only fix might be in an update, which probably will not come, as I beleive they have said they are not going to release anything new or something like that, and that people should do a fork or something, but I am not skilled or smart enough to be able to do anything bout it. I guess I would have to wait it out or deal with it lol.

**Comment by dmf444** [comment] 2020-04-12 17:16
Nah, I'm just busy. Something will come, eventually

**Comment by 34486** [comment] 2020-04-12 22:31
;o Awesome! No rush though!!!

**Comment by dmf444** [comment] 2020-04-16 16:07
JellyDoge, I copied your setup directly, you need to reformat your JSON file, as follows:

```
{
  "alarm-4min": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-4min", "stream": true}]},
  "alarm-1min": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-1min", "stream": true}]},
  "alarm-10sec": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-10sec", "stream": true}]},
  "alarm-lockdown": {"category": "master", "sounds": [{"name": "worldcontrol:alarm-lockdown", "stream": true}]}
}
```

**Comment by dmf444** [comment] 2020-04-16 16:12
@34486 If you have a chance, can you join our discord? I want to fix this issue, but need to be a bit more hands on, seeing as I can't replicate it in dev

**Comment by 34486** [comment] 2020-04-17 12:22
Yes, I will try your setup that you reformatted of JellyDoge's as well.

**Comment by 34486** [comment] 2020-04-18 17:31
Hey, works now, server side and client side! The configuration that JellyDoge made and youi reformatted works! Thank you!

**Closed as completed** 2020-05-06 20:02 UTC
Labels: help wanted
